Update Race Status
scrambledeggs/iole-trails pull request #5
Opened 2022-11-25 06:25 UTC by iole-geil

Update `race.status` with validations

2022-11-29 11:42 UTC, joppetburger approved these changes
+1 yung mga unless lang ule

2022-12-02 04:52 UTC, iole-geil commented
> +1 yung mga unless lang ule

Resolved in this [branch/commit](https://github.com/scrambledeggs/iole-trails/pull/7/commits/0dccf19cd079450fd6e4ebba5a2ddf0eefcca7ee)

2022-12-02 06:07 UTC, alecguintu requested changes

2022-12-02 06:07 UTC, alecguintu commented on app/views/races/show.html.erb
> +<% end %>
Better indent this so you know it's inside the if condition

2022-12-02 06:07 UTC, alecguintu commented on app/views/races/show.html.erb
> +<% if @race.status_NEW? %>
You can also use `<%- %>` with `-` so it does not create a space upon printing the html. Check on inspect elements. :)

2022-12-05 01:31 UTC, iole-geil commented on app/views/races/show.html.erb
> +<% end %>
Updated in [this commit](https://github.com/scrambledeggs/iole-trails/pull/7/commits/59df0b846c001ec185c33f73038c1832e3bdf0a9)

2022-12-15 03:42 UTC, iole-geil commented on app/views/races/show.html.erb
> +<% if @race.status_NEW? %>
Based on discussion, I will accommodate this feedback in a different branch and PR later.

2022-12-15 08:59 UTC, alecguintu approved these changes

2022-12-15 09:25 UTC, merged