Races, Runs, Practices updates
scrambledeggs/iole-trails pull request #7
Opened 2022-11-28 10:15 UTC by iole-geil

Other updates

2022-12-02 06:44 UTC, alecguintu requested changes

2022-12-02 06:44 UTC, alecguintu commented on app/controllers/races_controller.rb
> +    render :edit, status: :unprocessable_entity and return !@race.errors.include?(:status)
Kulang ata nang `if` ito.

2022-12-05 01:30 UTC, iole-geil commented on app/controllers/races_controller.rb
> +    render :edit, status: :unprocessable_entity and return !@race.errors.include?(:status)
Corrected in [this commit](https://github.com/scrambledeggs/iole-trails/pull/7/commits/d9ea35b4d0f2f7f66a975fc3d8673b34909d65f5)

2022-12-15 08:59 UTC, alecguintu approved these changes

2022-12-15 09:55 UTC, merged